---
title: "leaflet Example"
author: "Charlotte Looby"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidycensus)
library(tidyverse)
library(knitr)
library(leaflet) #New
library(sf) #New
library(leafem) #New

knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


## Median age by State, Census 2020

```{r Get age20 shape files}
#Get median age for all people

age20_shape <- get_decennial(geography = "state", 
                       variables = "P13_001N", 
                       year = 2020,
                       sumfile = "dhc",
                       geometry = TRUE) %>% #Gets shapes for mapping  
  st_transform(crs = 4326) #Changes target Coordinate Reference System (World Geodetic System 1984 (WGS 84))
  
```

```{r Create map, fig.height=10, fig.width=12}
#Create RColorBrewer palette(s)
age_pal <- colorNumeric(palette = "Blues", 
                        domain = age20_shape$value)

# age_pal <- colorNumeric(palette = "BuPu", 
#                         domain = age20_shape$value)
# 
# age_pal <- colorNumeric(palette = "RdYlGn", 
#                         domain = age20_shape$value)

#Make the map
leaflet() %>%
  addTiles() %>% #setup default OpenStreetMap
  addProviderTiles(providers$Esri.WorldImagery, group="WorldImagery") %>%
  addMouseCoordinates() %>% 
  addScaleBar(position = "topright") %>%
  # addProviderTiles(providers$Stadia.StamenToner, group="StamenToner") %>%
  # addProviderTiles(providers$Esri.NatGeoWorldMap, group="NatGeo") %>%
  
  addPolygons(data = age20_shape,
              group = "States",
              color = "black", weight = 2, opacity = 1,
              fill = FALSE) %>%
  
  # addPolygons(data = age20_shape,
  #             group = "Median age",
  #             color = "blue", weight = 2, opacity = 1,
  #             fillColor = ~age_pal(age20_shape$value), fillOpacity = 1) %>%
  
  addPolygons(data = age20_shape,
              group = "Median age",
              color = "blue", weight = 2, opacity = 1,
              fillColor = ~age_pal(age20_shape$value), fillOpacity = 1,
              popup = paste0(age20_shape$NAME, " median age: ", age20_shape$value)) %>%
  
  addLegend(position = "bottomright",
            pal = age_pal,
            values = age20_shape$value,
            opacity = 1,
            title = "Median age (Census 2020)") %>%
  
  # addLayersControl(
  #   baseGroups = c("WorldImagery", "OSM (default)")
  # ) %>%

  # addLayersControl(
  #   baseGroups = c("WorldImagery", "OSM (default)"),
  #   options = layersControlOptions(collapsed = FALSE)
  # ) %>%

  addLayersControl(
    baseGroups = c("WorldImagery", "OSM (default)"),
    options = layersControlOptions(collapsed = FALSE),
    overlayGroups = c("States", "Median age")
  )
```

## Percent renters in population of Ohio counties

```{r lookup ACS}

#Get total population in occupied housing units, owned and rented, for counties in Ohio

lookup_acs <- load_variables(2022, "acs5", cache=TRUE)

ohio_pop <- get_acs(geography = "county",
                    state = "Ohio",
                    survey = "acs5", 
                    year = 2022,
                    variables = c("B25008_002", "B25008_003"),
                    geometry = TRUE) %>% 
  st_transform(crs = 4326)

ohio_pop_clean <- ohio_pop %>%
  select(-moe) %>%
  spread(variable, estimate) %>%
  mutate(POP_TOT = B25008_002 + B25008_003,
         PCT_OWN = round(B25008_002/POP_TOT*100, 1),
         PCT_RENT = round(B25008_003/POP_TOT*100, 1)) 
```

```{r Create Ohio map, fig.height=10, fig.width=12}
#Create RColorBrewer palette(s)
rent_pal <- colorNumeric(palette = "Oranges", 
                        domain = ohio_pop_clean$PCT_RENT)

#Make the map
leaflet() %>%
  addTiles() %>% #setup default OpenStreetMap
  addProviderTiles(providers$Esri.WorldImagery, group="WorldImagery") %>%
  addMouseCoordinates() %>% 
  addScaleBar(position = "topright") %>%
  
  addPolygons(data = ohio_pop_clean,
              group = "County outline",
              color = "blue", weight = 2, opacity = 1,
              fill = FALSE) %>%
  
  addPolygons(data = ohio_pop_clean,
              group = "Percent renters",
              color = "blue", weight = 2, opacity = 1,
              fillColor = ~rent_pal(ohio_pop_clean$PCT_RENT), fillOpacity = 1,
              popup = paste0(ohio_pop_clean$NAME, " percent renters: ", ohio_pop_clean$PCT_RENT, "%")) %>%
  
  addLegend(position = "bottomright",
            pal = rent_pal,
            values = ohio_pop_clean$PCT_RENT,
            opacity = 0.5,
            title = "Percent renters (2022 ACS 5-yr)") %>%
  
  addLayersControl(
    baseGroups = c("WorldImagery", "OSM (default)"),
    options = layersControlOptions(collapsed = FALSE),
    overlayGroups = c("County outline", "Percent renters")
  )
  
```


